(defpackage #:mahogany/tree
  (:use :cl
        #:alexandria
        #:iterate
        #:mahogany/log
        #:mahogany/util
        #:mahogany/wm-interface)
  (:export #:*split-frame-hook*
           #:*new-frame-hook*
           #:*remove-split-hook*
           #:*new-split-type*
           #:frame
           #:frame-at
           #:frame-x
           #:frame-y
           #:frame-width
           #:frame-height
           #:frame-parent
           #:layer-container
           #:make-layer-container
           #:destroy-layer-container
           #:layer-container-transfer-view
           #:layer-container-layer
           #:tree-output-add
           #:root-tree
           #:tree-frame
           #:tree-children
           #:tree-split-direction
           #:binary-tree-frame
           #:poly-tree-frame
           #:split-frame-v
           #:split-frame-h
           #:close-frame
           #:remove-frame
           #:swap-positions
           #:find-empty-frame
           #:find-focused-frame
           #:find-view-frame
           #:get-populated-frames
           #:root-frame-p
           #:topmost-frame-p
           #:find-root-frame
           #:find-topmost-frame
           #:find-output
           #:find-first-leaf
           #:mark-frame-focused
           #:unmark-frame-focused
           #:replace-frame
           #:reconfigure-node
           ;; View-frame functions / objects
           #:view-frame
           #:frame-surface
           #:frame-next
           #:frame-prev
           #:frame-find-layer
           #:find-frame-if
           #:output-container
           #:output-container-output
           #:output-node
           #:output-node-output
           #:set-fullscreen
           #:clear-fullscreen
           ;; scrolling strip
           #:strip-frame
           #:strip-cell
           #:strip-columns
           #:strip-column-cells
           #:strip-column-width
           #:strip-selected
           #:strip-selected-column
           #:strip-cells
           #:strip-layout
           #:strip-add-view
           #:strip-remove-cell
           #:strip-focus-target
           #:strip-move
           #:strip-set-width
           #:strip-adjust-height
           #:strip-consume
           #:strip-expel
           #:strip-take-column
           #:strip-add-column
           #:strip-reserved-top
           #:strip-reserved-bottom
           #:strip-fullscreen-view
           #:strip-offset
           #:cell-column
           #:cell-weight
           #:tree-output-add-strip
           #:*strip-layout-hook*
           #:*view-focus-hook*
           #:*strip-gap*
           #:*strip-default-width*
           #:*strip-width-presets*
           #:*strip-width-step*))
